import '../styles/globals.css';
import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Inter } from 'next/font/google';
import Providers from './Providers';
import AdminWraper from '@/components/AdminWraper';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Movitrone',
  description: 'Generated By abdulra7manshaban@gmail.com',
};
export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const session = await getServerSession(authOptions)
  return (
    <html
      suppressHydrationWarning={true}
      lang={locale}
      dir={locale === 'ar' ? 'rtl' : 'ltr'}
    >
      <body
        suppressHydrationWarning={true}
        className={`${
          locale === 'ar' ? inter.className : inter.className
        }`}
      >
        <AntdRegistry>
          <Providers>
            <AdminWraper session={session}>{children}</AdminWraper>
          </Providers>
        </AntdRegistry>
      </body>
    </html>
  );
}
