import '../styles/globals.css';
import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Inter } from 'next/font/google';
import Providers from './Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Movitrone',
  description: 'Generated By abdulra7manshaban@gmail.com',
};
export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html
      suppressHydrationWarning={true}
      lang={locale}
      dir={locale === 'ar' ? 'rtl' : 'ltr'}
    >
      <body
        suppressHydrationWarning={true}
        className={`${locale === 'ar' ? inter.className : inter.className}`}
      >
        <AntdRegistry>
          <Providers>{children}</Providers>
        </AntdRegistry>
      </body>
    </html>
  );
}
